name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.7', '3.0', '3.1', '3.2']
        rspec-version: ['~> 3.12.0']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        bundle config set --local without 'development'
        bundle install

    - name: Set RSpec version
      run: |
        bundle remove rspec
        bundle add rspec --version "${{ matrix.rspec-version }}"

    - name: Run tests
      run: bundle exec rspec
